packages:
  - name: sample
    actions:
      - name: hello
        runtime: 'nodejs:default'
environment:
  #LOG_DESTINATIONS: ${LOG_DESTINATIONS}
  #LOG_DESTINATIONS: '[{"logtail":{"token":"uAHyJLbRPe4JnL9HVethjnTa"}}]'
  OBB_FUNCTION_SECRET: "${OBB_FUNCTION_SECRET}"
  TESTVAR: "1"



