packages:
  - name: sample
    actions:
      - name: hello
        runtime: 'nodejs:default'
environment:
  #LOG_DESTINATIONS: ${LOG_DESTINATIONS}
  LOG_DESTINATIONS: '[{"logtail":{"name: "Function test logs","token":"uAHyJLbRPe4JnL9HVethjnTa"}}]'
